apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      nodeSelector:
        pool: {{ .Values.deployment.node_selector }}
      subdomain: primary
      containers:
        - name: redis
          env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          command:
            - "redis-server"
          args:
            - --requirepass
            - $(PASSWORD)
            - "--protected-mode"
            - "no"
