apiVersion: v1
kind: Service
metadata:
  name: slave
  labels:
    app: slave
spec:
  type: LoadBalancer
  ports:
  - name: redis
    targetPort: {{ .Values.deployment.targetPort }}
    protocol: TCP
    port: {{ .Values.deployment.port }}
  selector:
    name: redis-slave